# fly.toml file generated for katbin on 2022-05-06T17:46:21+05:30

app = "katbin"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

# [deploy]
#   release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "katbin.fly.dev"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 10000
    soft_limit = 6000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
